### ISSUE TITLE
Confusion in AUR

### ISSUE THREAD

**Issue by Alerymin** [n3oney/discord-update-skip#1]
The Discord version targets Discord
But the Discord Canary version targets Discord PTB
And it looks like the Discord PTB version targets the Discord version

Can you fix this please ?

**Comment by n3oney** [comment]
Sorry, this must've been a mistake on my end.
Unfortunately I won't have access to my PC until tuesday, but I'll try to fix it from my phone ASAP.
Thanks for bringing this up!

**Comment by n3oney** [comment]
Sorry, this must've been a mistake on my end.
Unfortunately I won't have access to my PC until tuesday, but I'll try to fix it from my phone ASAP.
Thanks for bringing this up!

**Comment by n3oney** [comment]
Hello.
I've pushed an update to the AUR, however due to lack of access to my PC I'm unable to verify whether all is working properly.
If this has fixed the problem, please close issue. Thank you!

**Comment by n3oney** [comment]
Since this didn't get any updates, I'll assume I fixed it.

**Comment by Alerymin** [comment]
Sorry for the very very late answer (I never watch my github notifications), I tested everything and you fixed it, thanks
